<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.__4ZhAa' shared service.

return $this->privates['.service_locator.__4ZhAa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'categoriesManager' => ['privates', 'App\\Manager\\CategoriesManager', 'getCategoriesManagerService.php', true],
], [
    'categoriesManager' => 'App\\Manager\\CategoriesManager',
]);
