<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Manager\CategoriesManager' shared autowired service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Manager'.\DIRECTORY_SEPARATOR.'CategoriesManager.php';

return $this->privates['App\\Manager\\CategoriesManager'] = new \App\Manager\CategoriesManager(($this->services['doctrine'] ?? $this->getDoctrineService()));
