<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.88cjjf1' shared service.

return $this->privates['.service_locator.88cjjf1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'reason' => ['privates', '.errored..service_locator.88cjjf1.App\\Entity\\Reason', NULL, 'Cannot autowire service ".service_locator.88cjjf1": it references class "App\\Entity\\Reason" but no such service exists.'],
], [
    'reason' => 'App\\Entity\\Reason',
]);
