<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.hY90s__' shared service.

return $this->privates['.service_locator.hY90s__'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'entity' => ['privates', '.errored..service_locator.hY90s__.App\\Entity\\CategoryDocument', NULL, 'Cannot autowire service ".service_locator.hY90s__": it references class "App\\Entity\\CategoryDocument" but no such service exists.'],
], [
    'entity' => 'App\\Entity\\CategoryDocument',
]);
