<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.cDoGPH3.App\Entity\Congres' shared service.

$this->throw('Cannot autowire service ".service_locator.cDoGPH3": it references class "App\\Entity\\Congres" but no such service exists.');
