<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZmV7yxi\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZmV7yxi/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerZmV7yxi.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerZmV7yxi\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerZmV7yxi\App_KernelProdContainer([
    'container.build_hash' => 'ZmV7yxi',
    'container.build_id' => '0d25ae98',
    'container.build_time' => 1599236504,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZmV7yxi');
