<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPz8FJ7x\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPz8FJ7x/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerPz8FJ7x.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerPz8FJ7x\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerPz8FJ7x\srcApp_KernelProdContainer([
    'container.build_hash' => 'Pz8FJ7x',
    'container.build_id' => 'e9d1778e',
    'container.build_time' => 1612186908,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPz8FJ7x');
