<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.3m502IA' shared service.

return $this->privates['.service_locator.3m502IA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'produit' => ['privates', '.errored..service_locator.3m502IA.App\\Entity\\Produit', NULL, 'Cannot autowire service ".service_locator.3m502IA": it references class "App\\Entity\\Produit" but no such service exists.'],
    'produitRepository' => ['privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService.php', true],
], [
    'produit' => 'App\\Entity\\Produit',
    'produitRepository' => 'App\\Repository\\ProduitRepository',
]);
