<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.3CWM4Lz.App\Entity\Document' shared service.

$this->throw('Cannot autowire service ".service_locator.3CWM4Lz": it references class "App\\Entity\\Document" but no such service exists.');
