<?php

namespace ContainerU9C8Tig;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_V6uKiCpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.v6uKiCp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.v6uKiCp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CongresController::documents' => ['privates', '.service_locator.7tbPGCD', 'get_ServiceLocator_7tbPGCDService', true],
            'App\\Controller\\CongresController::home' => ['privates', '.service_locator.RRqMnkj', 'get_ServiceLocator_RRqMnkjService', true],
            'App\\Controller\\CongresController::questionSend' => ['privates', '.service_locator.oBpsT09', 'get_ServiceLocator_OBpsT09Service', true],
            'App\\Controller\\MeetingController::meetingAccept' => ['privates', '.service_locator.oBpsT09', 'get_ServiceLocator_OBpsT09Service', true],
            'App\\Controller\\MeetingController::meetingRefuse' => ['privates', '.service_locator.oBpsT09', 'get_ServiceLocator_OBpsT09Service', true],
            'App\\Controller\\PlanningController::sendMeeting' => ['privates', '.service_locator.oBpsT09', 'get_ServiceLocator_OBpsT09Service', true],
            'App\\Controller\\PlanningController::userPlanning' => ['privates', '.service_locator.RRqMnkj', 'get_ServiceLocator_RRqMnkjService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'App\\Controller\\admin\\AdminController::editReason' => ['privates', '.service_locator.mRogL1X', 'get_ServiceLocator_MRogL1XService', true],
            'App\\Controller\\admin\\AdminController::editcatDoc' => ['privates', '.service_locator.nMtx1HI', 'get_ServiceLocator_NMtx1HIService', true],
            'App\\Controller\\admin\\AdminController::editcatUser' => ['privates', '.service_locator.h8xoP2B', 'get_ServiceLocator_H8xoP2BService', true],
            'App\\Controller\\admin\\CongresController::delete' => ['privates', '.service_locator.WTruJyW', 'get_ServiceLocator_WTruJyWService', true],
            'App\\Controller\\admin\\DocumentController::delete' => ['privates', '.service_locator.EP3KAvc', 'get_ServiceLocator_EP3KAvcService', true],
            'App\\Controller\\admin\\DocumentController::editDocument' => ['privates', '.service_locator.EP3KAvc', 'get_ServiceLocator_EP3KAvcService', true],
            'App\\Controller\\admin\\UserController::delete' => ['privates', '.service_locator.hEwcf7A', 'get_ServiceLocator_HEwcf7AService', true],
            'App\\Controller\\admin\\UserController::edit' => ['privates', '.service_locator.hEwcf7A', 'get_ServiceLocator_HEwcf7AService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\CongresController:documents' => ['privates', '.service_locator.7tbPGCD', 'get_ServiceLocator_7tbPGCDService', true],
            'App\\Controller\\CongresController:home' => ['privates', '.service_locator.RRqMnkj', 'get_ServiceLocator_RRqMnkjService', true],
            'App\\Controller\\CongresController:questionSend' => ['privates', '.service_locator.oBpsT09', 'get_ServiceLocator_OBpsT09Service', true],
            'App\\Controller\\MeetingController:meetingAccept' => ['privates', '.service_locator.oBpsT09', 'get_ServiceLocator_OBpsT09Service', true],
            'App\\Controller\\MeetingController:meetingRefuse' => ['privates', '.service_locator.oBpsT09', 'get_ServiceLocator_OBpsT09Service', true],
            'App\\Controller\\PlanningController:sendMeeting' => ['privates', '.service_locator.oBpsT09', 'get_ServiceLocator_OBpsT09Service', true],
            'App\\Controller\\PlanningController:userPlanning' => ['privates', '.service_locator.RRqMnkj', 'get_ServiceLocator_RRqMnkjService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'App\\Controller\\admin\\AdminController:editReason' => ['privates', '.service_locator.mRogL1X', 'get_ServiceLocator_MRogL1XService', true],
            'App\\Controller\\admin\\AdminController:editcatDoc' => ['privates', '.service_locator.nMtx1HI', 'get_ServiceLocator_NMtx1HIService', true],
            'App\\Controller\\admin\\AdminController:editcatUser' => ['privates', '.service_locator.h8xoP2B', 'get_ServiceLocator_H8xoP2BService', true],
            'App\\Controller\\admin\\CongresController:delete' => ['privates', '.service_locator.WTruJyW', 'get_ServiceLocator_WTruJyWService', true],
            'App\\Controller\\admin\\DocumentController:delete' => ['privates', '.service_locator.EP3KAvc', 'get_ServiceLocator_EP3KAvcService', true],
            'App\\Controller\\admin\\DocumentController:editDocument' => ['privates', '.service_locator.EP3KAvc', 'get_ServiceLocator_EP3KAvcService', true],
            'App\\Controller\\admin\\UserController:delete' => ['privates', '.service_locator.hEwcf7A', 'get_ServiceLocator_HEwcf7AService', true],
            'App\\Controller\\admin\\UserController:edit' => ['privates', '.service_locator.hEwcf7A', 'get_ServiceLocator_HEwcf7AService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\CongresController::documents' => '?',
            'App\\Controller\\CongresController::home' => '?',
            'App\\Controller\\CongresController::questionSend' => '?',
            'App\\Controller\\MeetingController::meetingAccept' => '?',
            'App\\Controller\\MeetingController::meetingRefuse' => '?',
            'App\\Controller\\PlanningController::sendMeeting' => '?',
            'App\\Controller\\PlanningController::userPlanning' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\admin\\AdminController::editReason' => '?',
            'App\\Controller\\admin\\AdminController::editcatDoc' => '?',
            'App\\Controller\\admin\\AdminController::editcatUser' => '?',
            'App\\Controller\\admin\\CongresController::delete' => '?',
            'App\\Controller\\admin\\DocumentController::delete' => '?',
            'App\\Controller\\admin\\DocumentController::editDocument' => '?',
            'App\\Controller\\admin\\UserController::delete' => '?',
            'App\\Controller\\admin\\UserController::edit' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\CongresController:documents' => '?',
            'App\\Controller\\CongresController:home' => '?',
            'App\\Controller\\CongresController:questionSend' => '?',
            'App\\Controller\\MeetingController:meetingAccept' => '?',
            'App\\Controller\\MeetingController:meetingRefuse' => '?',
            'App\\Controller\\PlanningController:sendMeeting' => '?',
            'App\\Controller\\PlanningController:userPlanning' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\admin\\AdminController:editReason' => '?',
            'App\\Controller\\admin\\AdminController:editcatDoc' => '?',
            'App\\Controller\\admin\\AdminController:editcatUser' => '?',
            'App\\Controller\\admin\\CongresController:delete' => '?',
            'App\\Controller\\admin\\DocumentController:delete' => '?',
            'App\\Controller\\admin\\DocumentController:editDocument' => '?',
            'App\\Controller\\admin\\UserController:delete' => '?',
            'App\\Controller\\admin\\UserController:edit' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
