<?php

namespace ContainerU9C8Tig;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EP3KAvcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EP3KAvc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EP3KAvc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'document' => ['privates', '.errored..service_locator.EP3KAvc.App\\Entity\\Document', NULL, 'Cannot autowire service ".service_locator.EP3KAvc": it references class "App\\Entity\\Document" but no such service exists.'],
        ], [
            'document' => 'App\\Entity\\Document',
        ]);
    }
}
