<?php

namespace ContainerU9C8Tig;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoryUserService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.h8xoP2B.App\Entity\CategoryUser' shared service.
     *
     * @return \App\Entity\CategoryUser
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.h8xoP2B": it references class "App\\Entity\\CategoryUser" but no such service exists.');
    }
}
