<?php

namespace ContainerU9C8Tig;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCongresManagerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Manager\CongresManager' shared autowired service.
     *
     * @return \App\Manager\CongresManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Manager/CongresManager.php';

        return $container->privates['App\\Manager\\CongresManager'] = new \App\Manager\CongresManager(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
