<?php

namespace ContainerU9C8Tig;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCongresController2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\admin\CongresController' shared autowired service.
     *
     * @return \App\Controller\admin\CongresController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/admin/CongresController.php';

        $container->services['App\\Controller\\admin\\CongresController'] = $instance = new \App\Controller\admin\CongresController(($container->privates['App\\Manager\\CongresManager'] ?? $container->load('getCongresManagerService')), ($container->privates['App\\Manager\\UserManager'] ?? $container->load('getUserManagerService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\admin\\CongresController', $container));

        return $instance;
    }
}
