<?php

namespace ContainerU9C8Tig;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCongresService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.WTruJyW.App\Entity\Congres' shared service.
     *
     * @return \App\Entity\Congres
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.WTruJyW": it references class "App\\Entity\\Congres" but no such service exists.');
    }
}
