<?php

namespace ContainerU9C8Tig;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCryptService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Crypt' shared autowired service.
     *
     * @return \App\Service\Crypt
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/Crypt.php';

        return $container->privates['App\\Service\\Crypt'] = new \App\Service\Crypt();
    }
}
