<?php

namespace ContainerU9C8Tig;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDocEditTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\Back\DocEditType' shared autowired service.
     *
     * @return \App\Form\Back\DocEditType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Back/DocEditType.php';

        return $container->privates['App\\Form\\Back\\DocEditType'] = new \App\Form\Back\DocEditType();
    }
}
