<?php

namespace ContainerU9C8Tig;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRefuseMeetingTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\Front\RefuseMeetingType' shared autowired service.
     *
     * @return \App\Form\Front\RefuseMeetingType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Front/RefuseMeetingType.php';

        return $container->privates['App\\Form\\Front\\RefuseMeetingType'] = new \App\Form\Front\RefuseMeetingType();
    }
}
