<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.mZAX5si.App\Entity\Produit' shared service.

$this->throw('Cannot autowire service ".service_locator.mZAX5si": it references class "App\\Entity\\Produit" but no such service exists.');
