<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.IISA5Q3' shared service.

return $this->privates['.service_locator.IISA5Q3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'entity' => ['privates', '.errored..service_locator.IISA5Q3.App\\Entity\\CategoryUser', NULL, 'Cannot autowire service ".service_locator.IISA5Q3": it references class "App\\Entity\\CategoryUser" but no such service exists.'],
], [
    'entity' => 'App\\Entity\\CategoryUser',
]);
