<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.cDoGPH3' shared service.

return $this->privates['.service_locator.cDoGPH3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'congres' => ['privates', '.errored..service_locator.cDoGPH3.App\\Entity\\Congres', NULL, 'Cannot autowire service ".service_locator.cDoGPH3": it references class "App\\Entity\\Congres" but no such service exists.'],
    'documentManager' => ['privates', 'App\\Manager\\DocumentManager', 'getDocumentManagerService.php', true],
    'meetingManager' => ['privates', 'App\\Manager\\MeetingManager', 'getMeetingManagerService.php', true],
], [
    'congres' => 'App\\Entity\\Congres',
    'documentManager' => 'App\\Manager\\DocumentManager',
    'meetingManager' => 'App\\Manager\\MeetingManager',
]);
