<?php

namespace ContainerZmV7yxi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NMtx1HIService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.nMtx1HI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nMtx1HI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entity' => ['privates', '.errored..service_locator.nMtx1HI.App\\Entity\\CategoryDocument', NULL, 'Cannot autowire service ".service_locator.nMtx1HI": it references class "App\\Entity\\CategoryDocument" but no such service exists.'],
        ], [
            'entity' => 'App\\Entity\\CategoryDocument',
        ]);
    }
}
