<?php

namespace ContainerZmV7yxi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7tbPGCDService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.7tbPGCD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7tbPGCD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categoriesManager' => ['privates', 'App\\Manager\\CategoriesManager', 'getCategoriesManagerService', true],
        ], [
            'categoriesManager' => 'App\\Manager\\CategoriesManager',
        ]);
    }
}
