<?php

namespace ContainerZmV7yxi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OBpsT09Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.oBpsT09' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oBpsT09'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'crypt' => ['privates', 'App\\Service\\Crypt', 'getCryptService', true],
            'mailer' => ['services', 'swiftmailer.mailer.default', 'getSwiftmailer_Mailer_DefaultService', true],
        ], [
            'crypt' => 'App\\Service\\Crypt',
            'mailer' => '?',
        ]);
    }
}
