<?php

namespace ContainerZmV7yxi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WTruJyWService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.WTruJyW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WTruJyW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'congres' => ['privates', '.errored..service_locator.WTruJyW.App\\Entity\\Congres', NULL, 'Cannot autowire service ".service_locator.WTruJyW": it references class "App\\Entity\\Congres" but no such service exists.'],
            'documentManager' => ['privates', 'App\\Manager\\DocumentManager', 'getDocumentManagerService', true],
            'meetingManager' => ['privates', 'App\\Manager\\MeetingManager', 'getMeetingManagerService', true],
        ], [
            'congres' => 'App\\Entity\\Congres',
            'documentManager' => 'App\\Manager\\DocumentManager',
            'meetingManager' => 'App\\Manager\\MeetingManager',
        ]);
    }
}
