<?php

namespace ContainerZmV7yxi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMeetingManagerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Manager\MeetingManager' shared autowired service.
     *
     * @return \App\Manager\MeetingManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Manager/MeetingManager.php';

        return $container->privates['App\\Manager\\MeetingManager'] = new \App\Manager\MeetingManager(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
