<?php

namespace ContainerZmV7yxi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReasonService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.mRogL1X.App\Entity\Reason' shared service.
     *
     * @return \App\Entity\Reason
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.mRogL1X": it references class "App\\Entity\\Reason" but no such service exists.');
    }
}
