<?php

namespace ContainerZmV7yxi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserCreationTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\Back\UserCreationType' shared autowired service.
     *
     * @return \App\Form\Back\UserCreationType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Back/UserCreationType.php';

        return $container->privates['App\\Form\\Back\\UserCreationType'] = new \App\Form\Back\UserCreationType();
    }
}
