<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPXvypQD\srcApp_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPXvypQD/srcApp_KernelDevContainer.php') {
    touch(__DIR__.'/ContainerPXvypQD.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevContainer::class, false)) {
    \class_alias(\ContainerPXvypQD\srcApp_KernelDevContainer::class, srcApp_KernelDevContainer::class, false);
}

return new \ContainerPXvypQD\srcApp_KernelDevContainer([
    'container.build_hash' => 'PXvypQD',
    'container.build_id' => 'd570c504',
    'container.build_time' => 1612188038,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPXvypQD');
