<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXxRRETh\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXxRRETh/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXxRRETh.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXxRRETh\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXxRRETh\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XxRRETh',
    'container.build_id' => '11914a0e',
    'container.build_time' => 1612195833,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXxRRETh');
