<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZrF6Tg2\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZrF6Tg2/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZrF6Tg2.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZrF6Tg2\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZrF6Tg2\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ZrF6Tg2',
    'container.build_id' => 'e23cfaa6',
    'container.build_time' => 1612188467,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZrF6Tg2');
