<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors~app~carousel~modal~slider.js',
                '/build/vendors~app.js',
                '/build/app.js',
            ],
            'css' => [
                '/build/vendors~app.css',
                '/build/app.css',
            ],
        ],
        'modal' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors~app~carousel~modal~slider.js',
                '/build/modal.js',
            ],
        ],
        'carousel' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors~app~carousel~modal~slider.js',
                '/build/vendors~carousel.js',
                '/build/carousel.js',
            ],
        ],
        'slider' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors~app~carousel~modal~slider.js',
                '/build/slider.js',
            ],
        ],
        'admin' => [
            'js' => [
                '/build/runtime.js',
            ],
            'css' => [
                '/build/admin.css',
            ],
        ],
    ],
],

]];
