name: deploy
on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD}}
          script: |
            cd parc.agence.surf/
            sudo git pull origin dev
            php bin/console c:c
