<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Congres extends \App\Entity\Congres implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Congres' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Congres' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Congres' . "\0" . 'start_date', '' . "\0" . 'App\\Entity\\Congres' . "\0" . 'end_date', '' . "\0" . 'App\\Entity\\Congres' . "\0" . 'created_at', '' . "\0" . 'App\\Entity\\Congres' . "\0" . 'security_code', '' . "\0" . 'App\\Entity\\Congres' . "\0" . 'users', '' . "\0" . 'App\\Entity\\Congres' . "\0" . 'documents', '' . "\0" . 'App\\Entity\\Congres' . "\0" . 'meetings', '' . "\0" . 'App\\Entity\\Congres' . "\0" . 'durationMeeting', '' . "\0" . 'App\\Entity\\Congres' . "\0" . 'hour_min', '' . "\0" . 'App\\Entity\\Congres' . "\0" . 'hour_max'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Congres' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Congres' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Congres' . "\0" . 'start_date', '' . "\0" . 'App\\Entity\\Congres' . "\0" . 'end_date', '' . "\0" . 'App\\Entity\\Congres' . "\0" . 'created_at', '' . "\0" . 'App\\Entity\\Congres' . "\0" . 'security_code', '' . "\0" . 'App\\Entity\\Congres' . "\0" . 'users', '' . "\0" . 'App\\Entity\\Congres' . "\0" . 'documents', '' . "\0" . 'App\\Entity\\Congres' . "\0" . 'meetings', '' . "\0" . 'App\\Entity\\Congres' . "\0" . 'durationMeeting', '' . "\0" . 'App\\Entity\\Congres' . "\0" . 'hour_min', '' . "\0" . 'App\\Entity\\Congres' . "\0" . 'hour_max'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Congres $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): \App\Entity\Congres
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getStartDate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStartDate', []);

        return parent::getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setStartDate(\DateTimeInterface $start_date): \App\Entity\Congres
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStartDate', [$start_date]);

        return parent::setStartDate($start_date);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndDate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndDate', []);

        return parent::getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndDate(\DateTimeInterface $end_date): \App\Entity\Congres
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndDate', [$end_date]);

        return parent::setEndDate($end_date);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTimeInterface $created_at): \App\Entity\Congres
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$created_at]);

        return parent::setCreatedAt($created_at);
    }

    /**
     * {@inheritDoc}
     */
    public function getSecurityCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSecurityCode', []);

        return parent::getSecurityCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setSecurityCode(string $security_code): \App\Entity\Congres
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSecurityCode', [$security_code]);

        return parent::setSecurityCode($security_code);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsers(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsers', []);

        return parent::getUsers();
    }

    /**
     * {@inheritDoc}
     */
    public function addUser(\App\Entity\user $user): \App\Entity\Congres
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUser', [$user]);

        return parent::addUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUser(\App\Entity\user $user): \App\Entity\Congres
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUser', [$user]);

        return parent::removeUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocuments(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocuments', []);

        return parent::getDocuments();
    }

    /**
     * {@inheritDoc}
     */
    public function addDocument(\App\Entity\Document $document): \App\Entity\Congres
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDocument', [$document]);

        return parent::addDocument($document);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDocument(\App\Entity\Document $document): \App\Entity\Congres
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDocument', [$document]);

        return parent::removeDocument($document);
    }

    /**
     * {@inheritDoc}
     */
    public function getMeetings(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMeetings', []);

        return parent::getMeetings();
    }

    /**
     * {@inheritDoc}
     */
    public function addMeeting(\App\Entity\Meeting $meeting): \App\Entity\Congres
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMeeting', [$meeting]);

        return parent::addMeeting($meeting);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMeeting(\App\Entity\Meeting $meeting): \App\Entity\Congres
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMeeting', [$meeting]);

        return parent::removeMeeting($meeting);
    }

    /**
     * {@inheritDoc}
     */
    public function getDurationMeeting(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDurationMeeting', []);

        return parent::getDurationMeeting();
    }

    /**
     * {@inheritDoc}
     */
    public function setDurationMeeting(\DateTimeInterface $durationMeeting): \App\Entity\Congres
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDurationMeeting', [$durationMeeting]);

        return parent::setDurationMeeting($durationMeeting);
    }

    /**
     * {@inheritDoc}
     */
    public function getHourMin(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHourMin', []);

        return parent::getHourMin();
    }

    /**
     * {@inheritDoc}
     */
    public function setHourMin(\DateTimeInterface $hour_min): \App\Entity\Congres
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHourMin', [$hour_min]);

        return parent::setHourMin($hour_min);
    }

    /**
     * {@inheritDoc}
     */
    public function getHourMax(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHourMax', []);

        return parent::getHourMax();
    }

    /**
     * {@inheritDoc}
     */
    public function setHourMax(\DateTimeInterface $hour_max): \App\Entity\Congres
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHourMax', [$hour_max]);

        return parent::setHourMax($hour_max);
    }

}
