<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Document extends \App\Entity\Document implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Document' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Document' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Document' . "\0" . 'about', '' . "\0" . 'App\\Entity\\Document' . "\0" . 'doc_name', '' . "\0" . 'App\\Entity\\Document' . "\0" . 'img', '' . "\0" . 'App\\Entity\\Document' . "\0" . 'congres', '' . "\0" . 'App\\Entity\\Document' . "\0" . 'number_download', '' . "\0" . 'App\\Entity\\Document' . "\0" . 'ref', '' . "\0" . 'App\\Entity\\Document' . "\0" . 'size', '' . "\0" . 'App\\Entity\\Document' . "\0" . 'created_at', '' . "\0" . 'App\\Entity\\Document' . "\0" . 'categoryDocuments'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Document' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Document' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Document' . "\0" . 'about', '' . "\0" . 'App\\Entity\\Document' . "\0" . 'doc_name', '' . "\0" . 'App\\Entity\\Document' . "\0" . 'img', '' . "\0" . 'App\\Entity\\Document' . "\0" . 'congres', '' . "\0" . 'App\\Entity\\Document' . "\0" . 'number_download', '' . "\0" . 'App\\Entity\\Document' . "\0" . 'ref', '' . "\0" . 'App\\Entity\\Document' . "\0" . 'size', '' . "\0" . 'App\\Entity\\Document' . "\0" . 'created_at', '' . "\0" . 'App\\Entity\\Document' . "\0" . 'categoryDocuments'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Document $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): \App\Entity\Document
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbout(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbout', []);

        return parent::getAbout();
    }

    /**
     * {@inheritDoc}
     */
    public function setAbout(?string $about): \App\Entity\Document
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAbout', [$about]);

        return parent::setAbout($about);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocName', []);

        return parent::getDocName();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocName(string $doc_name): \App\Entity\Document
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocName', [$doc_name]);

        return parent::setDocName($doc_name);
    }

    /**
     * {@inheritDoc}
     */
    public function getImg(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImg', []);

        return parent::getImg();
    }

    /**
     * {@inheritDoc}
     */
    public function setImg(string $img): \App\Entity\Document
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImg', [$img]);

        return parent::setImg($img);
    }

    /**
     * {@inheritDoc}
     */
    public function getCongres(): ?\App\Entity\congres
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCongres', []);

        return parent::getCongres();
    }

    /**
     * {@inheritDoc}
     */
    public function setCongres(?\App\Entity\congres $congres): \App\Entity\Document
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCongres', [$congres]);

        return parent::setCongres($congres);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumberDownload(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumberDownload', []);

        return parent::getNumberDownload();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumberDownload(?int $number_download): \App\Entity\Document
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumberDownload', [$number_download]);

        return parent::setNumberDownload($number_download);
    }

    /**
     * {@inheritDoc}
     */
    public function getRef(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRef', []);

        return parent::getRef();
    }

    /**
     * {@inheritDoc}
     */
    public function setRef(?string $ref): \App\Entity\Document
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRef', [$ref]);

        return parent::setRef($ref);
    }

    /**
     * {@inheritDoc}
     */
    public function getSize(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSize', []);

        return parent::getSize();
    }

    /**
     * {@inheritDoc}
     */
    public function setSize(?string $size): \App\Entity\Document
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSize', [$size]);

        return parent::setSize($size);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTimeInterface $created_at): \App\Entity\Document
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$created_at]);

        return parent::setCreatedAt($created_at);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategoryDocuments(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoryDocuments', []);

        return parent::getCategoryDocuments();
    }

    /**
     * {@inheritDoc}
     */
    public function addCategoryDocument(\App\Entity\CategoryDocument $categoryDocument): \App\Entity\Document
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCategoryDocument', [$categoryDocument]);

        return parent::addCategoryDocument($categoryDocument);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCategoryDocument(\App\Entity\CategoryDocument $categoryDocument): \App\Entity\Document
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCategoryDocument', [$categoryDocument]);

        return parent::removeCategoryDocument($categoryDocument);
    }

}
